### PR TITLE
Dl read computer list

### PR DESCRIPTION
**Pull request by delindell**
Can view, create, and delete computers per ticket #9 
Still need to tie in ability to only delete computers if they have never been assigned to an employee

### CODE REVIEW

**Comment by ronaldo1618** [comment]
👍

**Comment by zanebliss** [comment]
Looks good, but I'm wondering about issue #18. Shouldn't the user be able to view a read-only list of the computer resources if they are not authenticated? As it stands I cannot view the resources unless I am logged in @delindell.

**Comment by ronaldo1618** [comment]
👍 👍

**Review by zanebliss — APPROVED** [review]

**Review by stephencastaneda — APPROVED** [review]
Looks good!

**Pull request merged**
